### ISSUE TITLE
The physical server state can not change when I powered off the server.

### ISSUE THREAD

**Issue by pozhong** [ManageIQ/manageiq-providers-redfish#21]
I added debug log in method "physical_servers" in file  "../parser/physical_infra_manager.rb" as blow:
![image](https://user-images.githubusercontent.com/41723411/43246219-80027d92-90e3-11e8-9947-0655418aa786.png)

I refreshed physical server by "refresh" funtion in horizon, debug info is blow:
[----] I, [2018-07-26T01:42:17.207433 #3426:2ad0218df13c]  INFO -- : parse good_servers is:{:ems_id=>1, :ems_ref=>"/redfish/v1/Systems/1", :type=>"ManageIQ::Providers::Redfish::PhysicalInfraManager::PhysicalServer", :name=>"1", :health_state=>"OK", :power_state=>"Off", :hostname=>nil, :product_name=>"Huawei RH2288H V3", :manufacturer=>"Huawei", :machine_type=>"RH2288H V3", :model=>"RH2288H V3", :serial_number=>"2102310YJA6TJ1000048", :field_replaceable_unit=>"dummy", :raw_power_state=>"Off", :vendor=>"Huawei", :location_led_state=>nil}.

we can see the power state is "Off", but it is "On" in horizon and database.

**Comment by tadeboro** [comment]
I tested this and cannot replicate the problem. Steps I took:

 1. Run mock server that serves Redfish recording.
 2. Add new provider and wait for the initial refresh (this took about 30 seconds to terminate).
 3. Navigate to the details of one of the physical servers and take not of the power state field value (it was on `On` in this particular case).
 4. Patch selected server in the mock by flipping the `PowerState` field from `On` to `Off`.
 5. Request inventory refresh from the ManageIQ UI (**Configuration** -> **Refresh Relationships and Power States**).
 6. Wait for refresh to start and terminate (this again took about a 30 seconds).
 7. Refresh the web page to fetch fresh data from the database.
 8. Verify that server's power state field value is `Off`.

Can you please follow these steps and check if the power state is still not updating properly? You can of course use your physical server instead of mock (I just used it because it is faster to flip the power state using editor instead of playing with real server).

**Comment by pozhong** [comment]
Thank you, I follow your steps and use a mock server, it's ok!
I will check if physical server redfish api's problem.
