### ISSUE TITLE
root password and other fields for redfish / physical provisioning

### ISSUE THREAD

**Issue by daniel-wtd** [ManageIQ/manageiq-providers-redfish#91]
Hey everybody,

with the update to ivanchuk-1-beta1 the dialog for pxe installations changed.
I am not able to find, where I can customize it and allow some additional values like:

- hostname
- user
- passwords
- ip address

The dialog settings from "automation" for physical servers also does not represent the current "new" dialog for pxe installations. Is there some updated documentation somewhere or a hint where I can look at?

**Comment by tadeboro** [comment]
You can find the work-in-progress documentation at https://github.com/xlab-si/manageiq-redfish-docs (master branch should contain most of the Ivanchuck-related updates).

You cannot add new fields to the provisioning dialog since the provisioning process itself is fixed and can only handle the three inputs we already offer for customization. Besides, adding new fields like `hostname` makes little sense since they are operating system specific.

You should place your operating system customizations into (aptly named) customization template. ManageIQ will make sure the customizations are passed-down to the installation program of your operating system of choice.

On the side note: maybe you should try asking your questions on [gitter](https://gitter.im/ManageIQ/manageiq) or [ManageIQ discourse](http://talk.manageiq.org/) instead of opening issues on GitHub. Those communication channels are better suited for the things that may or may not be provider bugs.

**Comment by daniel-wtd** [comment]
I will do so, thanks a lot :)
